# Generated by Django 5.0.4 on 2024-05-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandeproduct',
            old_name='facture',
            new_name='commande',
        ),
    ]
