# Generated by Django 5.0.4 on 2024-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='paid',
            new_name='confirmer',
        ),
        migrations.RemoveField(
            model_name='users',
            name='FarstName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='LastName',
        ),
        migrations.AddField(
            model_name='users',
            name='CompletName',
            field=models.CharField(default=1, max_length=232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='telephone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
