# Generated by Django 5.0.4 on 2024-05-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_rename_paid_commande_confirmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Adresse',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
