# Generated by Django 5.0.4 on 2024-05-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Adresse',
            field=models.CharField(default='', max_length=132),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
