# Generated by Django 5.0.4 on 2024-05-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_users_adresse_alter_users_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='gmail',
        ),
    ]
