# Generated by Django 5.0.4 on 2024-05-19 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_remove_commande_save_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandeproduct',
            name='Adresse',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='commandeproduct',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commandeproduct',
            name='ville',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
