# Generated by Django 5.0.4 on 2024-05-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_alter_commande_client_commandeproduct_adresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='commandeproduct',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
    ]
