# Generated by Django 5.0.4 on 2024-05-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_commande_options_alter_commandeproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
