# Generated by Django 5.0.4 on 2024-05-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduct',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_commande', to='Shop.commande'),
        ),
    ]
