# Generated by Django 5.0.4 on 2024-05-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_alter_commandeproduct_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduct',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.commande'),
        ),
    ]
