# Generated by Django 5.0.4 on 2024-05-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_alter_commandeproduct_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
