# Generated by Django 5.0.4 on 2024-05-21 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_alter_produit_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commande',
            new_name='Facture',
        ),
        migrations.AlterModelOptions(
            name='commandeproduct',
            options={'verbose_name': 'commande', 'verbose_name_plural': 'commandes'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.RenameField(
            model_name='commandeproduct',
            old_name='commande',
            new_name='facture',
        ),
    ]
