# Generated by Django 5.0.4 on 2024-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_rename_commande_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduct',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandeproduct',
            name='total_a',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
