# Generated by Django 5.0.4 on 2024-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_commandeproduct_prix_achat_commandeproduct_total_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('sbj', models.TextField(max_length=32)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='commandeproduct',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='commandeproduct',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='commandeproduct',
            name='ville',
        ),
        migrations.AddField(
            model_name='facture',
            name='Adresse',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='ville',
            field=models.CharField(max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='descreption',
            field=models.TextField(max_length=200),
        ),
    ]
