# Generated by Django 5.0.4 on 2024-05-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_contact_remove_commandeproduct_adresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sbj',
            new_name='subj',
        ),
    ]
