# Generated by Django 5.0.4 on 2024-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_alter_contact_options_rename_sbj_contact_subj'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
