# Generated by Django 5.0.6 on 2024-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0023_alter_produit_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='promo',
        ),
        migrations.AddField(
            model_name='produit',
            name='TauxRemise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
