# Generated by Django 5.0.6 on 2024-06-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0024_remove_produit_promo_produit_tauxremise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduct',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_products', to='Shop.facture'),
        ),
    ]
